week1 hw1~5
Lidemy/mentor-program-5th-cmtilo pull request #2
Opened 2021-04-15 13:21 UTC by cmtilo

2021-04-16 15:45 UTC, cwc329 requested changes

2021-04-16 15:45 UTC, cwc329 commented on homeworks/week1/challenge1.sh
> +
挑戰題成功。

2021-04-16 15:45 UTC, cwc329 commented on homeworks/week1/hw1.md
>  接著提交 `git commit -am`
line 3
如果要表達這邊要傳入自己的網址，後面可以不用再加上網址。不然在閱讀上有點混淆。

2021-04-16 15:45 UTC, cwc329 commented on homeworks/week1/hw1.md
>  接著提交 `git commit -am`
另外，如果有新增移除檔案，只有 commit 有用嗎？

2021-04-16 15:45 UTC, cwc329 commented on homeworks/week1/hw1.md
>  再推到遠端 `git push origin`
你想要推到哪個 branch 呢？

2021-04-16 15:45 UTC, cwc329 commented on homeworks/week1/hw1.md
> +注意事項：新的檔案一定要 git add {檔名} 才會加進去！!
這種書寫方式不太好，如果作為說明文件會讓人不好找到這段話。

2021-04-16 15:45 UTC, cwc329 commented on homeworks/week1/hw1.md
> +注意事項：新的檔案一定要 git add {檔名} 才會加進去！!
這種書寫方式不太好，如果作為說明文件會讓人不好找到這段話。

2021-04-16 15:45 UTC, cwc329 commented on homeworks/week1/hw1.md
>  從week1 合併進去 master
那 merge 之後呢？

2021-04-16 15:45 UTC, cwc329 commented on homeworks/week1/hw3.md
> +教學：mkdir wifi → touch afu.js
這樣真的會在 wifi 的資料夾裡面建立 afu.js 嗎？

2021-04-16 15:45 UTC, cwc329 commented on homeworks/week1/hw3.md
> +:WQ 寫完後存檔離開
:Q 或者 :WQ 不會離開喔。

2021-04-16 15:45 UTC, cwc329 commented on homeworks/week1/hw4.md
> +`git commit -m {__}` 新建版本
如果要代表字串建議不要用 {} 包起來，這兩個符號在工程師之間有其他比較常見的含義。

2021-04-16 15:45 UTC, cwc329 commented on homeworks/week1/hw4.md
> +4 git add.
如果在比較上層的資料夾有改動怎麼辦？

2021-04-16 15:45 UTC, cwc329 commented on homeworks/week1/hw4.md
> +專案建立後,新增檔案也要記得加入→4→5
如果這段敘述可以再更具體的說明這些指令的功能、用意、前後關係會更好。

2021-04-16 15:46 UTC, cwc329 commented
挑戰題成功，恭喜！
不過建議把一些地方再補足，例如建立 afu.js 的地方。
還有要注意大小寫，因為這在電腦中會是不異樣的東西。

2021-04-17 02:32 UTC, cmtilo commented
> 挑戰題成功，恭喜！
> 不過建議把一些地方再補足，例如建立 afu.js 的地方。
> 還有要注意大小寫，因為這在電腦中會是不異樣的東西。

助教改的超認真~謝謝你~~好多沒想到的問題跟狀況，真是震驚！
感謝您！我再思考過重新整理

2021-04-17 14:23 UTC, cmtilo commented on homeworks/week1/hw3.md
> +教學：mkdir wifi → touch afu.js
改正：mkdir wifi → cd wifi → touch afu.js

2021-04-17 14:24 UTC, cmtilo commented on homeworks/week1/hw1.md
>  從week1 合併進去 master
改正：
git checkout master
git pull origin master
git branch -d week1

2021-04-17 14:25 UTC, cmtilo commented on homeworks/week1/hw3.md
> +:WQ 寫完後存檔離開
改正：vim
i INSERT模式,可輸入文字
esc 普通模式,可刪除可複製
:q 離開出來的方式
:wq 寫完後存檔離開

2021-04-17 14:51 UTC, cmtilo commented on homeworks/week1/hw4.md
> +4 git add.
@cwc329 註記一下：這個問題不太懂
是否要git dff 看更改那些？

2021-04-17 14:57 UTC, cmtilo commented on homeworks/week1/hw4.md
> +專案建立後,新增檔案也要記得加入→4→5
改正：
1 git init 初始化,開始版本控制
2 git status 查詢狀態
3 .gitignore 忽略的檔案,一般放使用者個人相關或作業系統檔
4 git add . 把所有檔案全加入版本控制
5 git commit -am "__" 加入版本控制+新建版本同時,但不會加入新增的檔,所以有新增檔案還是要用 git add
6 git log 可以看全部版本的作者.修改時間.內容

2021-04-17 17:17 UTC, cwc329 commented
可以在這個 branch 修改好之後再 push，
如果是這樣可以再 tag 我來看。
或者你也可以先自己 merge，之後再開新的 branch 來修改，然後再交一次作業，也可以 tag 我來看。

2021-04-18 03:36 UTC, merged

2021-04-18 04:03 UTC, cwc329 commented on homeworks/week1/hw4.md
> +4 git add.
well
working directory: week21/hw1/src/
modified: week21/hw1/index.html
這種狀況。